### ISSUE TITLE
Don't reference jslint_on_rails as .jslintrc example

### ISSUE THREAD

**Issue by kara-ryli** [rondevera/jslintmate#10]
I started using the code reference on the jslint_on_rails project for my .jslintrc file, but that file doesn't match the configuration options for jslint and, more importantly, at least one value (nomen) has its definition reversed.

**Comment by rondevera** [comment]
Hey Ryan,

Thanks for reporting this! The JSLint project has changed quite a few of its options recently, and reversed several behaviors. If you look at the latest dev build in JSLintMate's `development` branch, you'll find a collection of [default options files](https://github.com/rondevera/jslintmate/tree/development/Support/config) that use the latest options for each project. These will be released with the upcoming JSLintMate 1.3 release, but feel free to start using them sooner.

JSLintMate 1.2 only supports reading YAML options files, so just copy `jslint.yml` into your `~/.jslintrc`. JSLintMate 1.3 will support reading JSON files as well; `jslint.json` is just ported from `jslint.yml`.

Cheers,
Ron

**Comment by rondevera** [comment]
Hey Ryan,

JSLintMate 1.3 is now available, and includes a collection of [example options files](https://github.com/rondevera/jslintmate/tree/master/Support/config) for your perusal. Since the JSLint and JSHint projects have diverged on their options' semantics, these options files are specifically tailored for each.

http://rondevera.github.com/jslintmate/

Cheers,
Ron
